trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:

# 1. Checkout source code
- checkout: self
  displayName: 'Checkout Source Code'

 # 2. Install Python
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
    addToPath: true
  displayName: 'Setup Python 3.8' 

  # 3. Upgrade pip
- script: |
    python -m pip install --upgrade pip
  displayName: 'Upgrade pip'