trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:

# ============================================================
# STAGE 1: BUILD
# ============================================================
- stage: Build
  displayName: 'Build Application'

  jobs:
  - job: Build
    displayName: 'Build and Package'

    steps:

    # 1. Checkout
    - checkout: self
      displayName: 'Checkout Source Code'

    # 2. Python
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
      displayName: 'Setup Python'

    # 3. Upgrade pip
    - script: |
        python -m pip install --upgrade pip
      displayName: 'Upgrade pip'

      # 4. Install project dependencies
    - script: |
        pip install -r requirement.txt
      displayName: 'Install Dependencies'
    
    # 5. Install unit test dependencies
    - script: |
        pip install pytest
        pip install pytest-html
      displayName: 'Install Unit Test Dependencies'
  # ============================================================
# STAGE 2: UNIT TEST
# ============================================================

- stage: UnitTest
  displayName: 'Unit Testing'

  dependsOn: Build

  condition: succeeded()

  jobs:

  # ----------------------------------------------------------
  # JOB 1: Run Unit Tests
  # ----------------------------------------------------------

  - job: RunUnitTests
    displayName: 'Run Python Unit Tests'

    steps:

    # 5. Install unit test dependencies
      - script: |
          pip install pytest
          pip install pytest-html
        displayName: 'Install Unit Test Dependencies'

  # 6. Check Python file
      - script: |
          python -m py_compile app.py
          python -m py_compile house.py
        displayName: 'Validate Python Code'

        # 7. Create test result folder
      - script: |
          mkdir -p test-results
        displayName: 'Create Test Result Folder'
      
      # 8. Run 50 unit tests
      - script: |
          pytest tests/test_app_50_cases.py \
          -v \
          -ra \
          --junitxml=test-results/junit.xml \
          --html=test-results/unit-test-report.html \
          --self-contained-html
        displayName: 'Run 50 Unit Tests'
        continueOnError: "true"

      # 9. Publish unit test results
      - task: PublishTestResults@2
        condition: always()
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: 'test-results/junit.xml'
          testRunTitle: 'House Price Prediction Unit Tests'
          failTaskOnFailedTests: false
        displayName: 'Publish Unit Test Results'

      # 10. Publish HTML test report
      - task: PublishPipelineArtifact@1
        condition: always()
        inputs:
          targetPath: 'test-results'
          artifact: 'unit-test-report'
          publishLocation: 'pipeline'
        displayName: 'Publish Unit Test Report'
# ============================================================
# STAGE 4: DOCKER BUILD
# ============================================================

- stage: DockerBuild
  displayName: 'Docker Build'
  dependsOn: UnitTest
  condition: succeeded()
  variables:
  - group: houseprice-docker-vars

  jobs:
  - job: DockerBuild
    displayName: 'Build Docker Image'

    steps:

    # ========================================================
    # CHECKOUT SOURCE CODE
    # ========================================================

    - checkout: self
      displayName: 'Checkout Source Code'

    # ========================================================
    # CHECK DOCKER VERSION
    # ========================================================
    - script: |
        docker --version
      displayName: 'Check Docker Version'

    # ========================================================
    # VERIFY DOCKERFILE
    # ========================================================

    - script: |
        echo "Current directory:"
        pwd

        echo "Repository contents:"
        ls -la

        echo "Dockerfile:"
        ls -l dockerfile
      displayName: 'Verify Dockerfile'

    # ========================================================
    # BUILD DOCKER IMAGE
    # ========================================================

    - script: |
        docker build \
          -t likithacr-f7f2e3fbe3g6a7b5.azurecr.io/$(imageName):$(imageTag) \
          -f dockerfile \
          .
      displayName: 'Build Docker Image'

    # ========================================================
    # VERIFY DOCKER IMAGE
    # ========================================================

    - script: |
        docker images
      displayName: 'Verify Docker Image'

    # ========================================================
    # SAVE DOCKER IMAGE
    # ========================================================

    - script: |
        docker save \
          -o $(Build.ArtifactStagingDirectory)/docker-image.tar \
          likithacr-f7f2e3fbe3g6a7b5.azurecr.io/$(imageName):$(imageTag)
      displayName: 'Save Docker Image'

    # ========================================================
    # PUBLISH DOCKER IMAGE AS PIPELINE ARTIFACT
    # ========================================================

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Docker Image Artifact'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/docker-image.tar'
        artifact: 'docker-image'


# ============================================================
# STAGE 5: PUSH DOCKER IMAGE TO ACR
# ============================================================

- stage: PushToACR
  displayName: 'Push Docker Image to ACR'
  dependsOn: DockerBuild
  condition: succeeded()

  variables:
  - group: houseprice-docker-vars

  jobs:
  - job: PushDockerImage
    displayName: 'Push Image to Azure Container Registry'

    steps:

    # ========================================================
    # CHECKOUT SOURCE CODE
    # ========================================================
    - checkout: self
      displayName: 'Checkout Source Code'

    # ========================================================
    # DOWNLOAD DOCKER IMAGE ARTIFACT
    # ========================================================
    - download: current
      artifact: docker-image
      displayName: 'Download Docker Image Artifact'

    # ========================================================
    # LOAD DOCKER IMAGE
    # ========================================================
    - script: |
        docker load \
          -i $(Pipeline.Workspace)/docker-image/docker-image.tar

        echo "Docker image after loading:"
        docker images
      displayName: 'Load Docker Image'

    # ========================================================
    # LOGIN TO ACR USING REPOSITORY TOKEN
    # ========================================================

    - script: |
        echo "$(ACR_PASSWORD)" | docker login \
          likithacr-f7f2e3fbe3g6a7b5.azurecr.io \
          --username "$(ACR_USERNAME)" \
          --password-stdin
      displayName: 'Login to ACR'

    # ========================================================
    # PUSH DOCKER IMAGE TO ACR
    # ========================================================

    - script: |
        docker push \
          likithacr-f7f2e3fbe3g6a7b5.azurecr.io/$(imageName):$(imageTag)
      displayName: 'Push Docker Image to ACR'

    # ========================================================
    # VERIFY DOCKER IMAGE
    # ========================================================

    - script: |
        docker images
      displayName: 'Verify Docker Image'


# ## ============================================================
# # STAGE 4: DOCKER BUILD
# # ============================================================

# - stage: DockerBuild
#   displayName: 'Docker Build'

#   dependsOn: UnitTest

#   condition: succeeded()

#   variables:
#   - group: houseprice-docker-vars

#   jobs:

#   - job: DockerBuild
#     displayName: 'Build Docker Image'

#     steps:

#     - checkout: self
#       displayName: 'Checkout Source Code'

#     # ========================================================
#     # CHECK DOCKER VERSION
#     # ========================================================

#     - script: |
#         docker --version
#       displayName: 'Check Docker Version'

#     # ========================================================
#     # BUILD DOCKER IMAGE
#     # ========================================================

#     - script: |
#         docker build \
#           -f dockerfile \
#           -t likithacr-f7f2e3fbe3g6a7b5.azurecr.io/$(imageName):$(imageTag) \
#           -t likithacr-f7f2e3fbe3g6a7b5.azurecr.io/$(imageName):latest \
#           .
#       displayName: 'Build Docker Image'

#     # ========================================================
#     # VERIFY DOCKER IMAGE
#     # ========================================================

#     - script: |
#         docker images
#       displayName: 'Verify Docker Image'
# # ============================================================
# # STAGE 5: PUSH DOCKER IMAGE TO ACR
# # ============================================================

# - stage: PushToACR
#   displayName: 'Push Docker Image to ACR'

#   dependsOn: DockerBuild

#   condition: succeeded()

#   variables:
#   - group: houseprice-docker-vars

#   jobs:

#   - job: PushDockerImage
#     displayName: 'Push Image to Azure Container Registry'

#     steps:

#     - checkout: self
#       displayName: 'Checkout Source Code'

#     # ========================================================
#     # LOGIN TO ACR USING REPOSITORY TOKEN
#     # ========================================================

#     - script: |
#         echo "$(ACR_PASSWORD)" | docker login likithacr-f7f2e3fbe3g6a7b5.azurecr.io \
#           --username "$(ACR_USERNAME)" \
#           --password-stdin
#       displayName: 'Login to ACR'

#     - task: Docker@2
#       displayName: 'Build and Push Docker Image'
#       inputs:
#         command: 'buildAndPush'
#         repository: 'likithacr-f7f2e3fbe3g6a7b5.azurecr.io/$(imageName)'
#         Dockerfile: 'dockerfile'
#         buildContext: '$(Build.SourcesDirectory)'
#         tags: |
#           $(imageTag)
#           latest

      # # 11. Start Flask application
      # - script: |
      #     python app.py &
      #     sleep 10
      #     echo "Flask application started successfully"
      #   displayName: 'Start Flask Application'

# - stage: RunApplication
#   displayName: 'Run Flask Application'

#   dependsOn: UnitTest

#   condition: succeeded()

#   jobs:

#   - job: RunApplication
#     displayName: 'Start Flask Application'

#     steps:

#     - script: |
#         python app.py & 
#         sleep 10 
#         echo "Flask application started successfully"
#       displayName: 'Start Flask Application'